#!/bin/zsh

eng=$(dirname $0)/engine.rb

if [[ "$1" = "add" || "$1" = "ls" || "$1" = "rm" ]]
then
    echo $(ruby $eng $*)
else 
    ruby $eng $*
    if [ $? -eq 0 ]
    then
        cd $(ruby $eng $*)
    fi
fi
